//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AlfaModel", "FK_Users_CellGroup", "CellGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ALFA_Client.Entities.CellGroup), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ALFA_Client.Entities.Users), true)]
[assembly: EdmRelationshipAttribute("AlfaModel", "FK_Rooms_Floors", "Floors", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ALFA_Client.Entities.Floors), "Rooms", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ALFA_Client.Entities.Rooms), true)]
[assembly: EdmRelationshipAttribute("AlfaModel", "FK_Keys_Rooms", "Rooms", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ALFA_Client.Entities.Rooms), "Keys", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ALFA_Client.Entities.Keys), true)]
[assembly: EdmRelationshipAttribute("AlfaModel", "FK_Keys_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ALFA_Client.Entities.Users), "Keys", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ALFA_Client.Entities.Keys), true)]
[assembly: EdmRelationshipAttribute("AlfaModel", "FK_logRecs_Rooms", "Rooms", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ALFA_Client.Entities.Rooms), "logRecs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ALFA_Client.Entities.logRecs), true)]
[assembly: EdmRelationshipAttribute("AlfaModel", "FK_logRecs_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ALFA_Client.Entities.Users), "logRecs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ALFA_Client.Entities.logRecs), true)]
[assembly: EdmRelationshipAttribute("AlfaModel", "FK_Room_Categories", "RoomCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ALFA_Client.Entities.RoomCategories), "Rooms", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ALFA_Client.Entities.Rooms), true)]
[assembly: EdmRelationshipAttribute("AlfaModel", "FK_Users_Floor", "Floors", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ALFA_Client.Entities.Floors), "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ALFA_Client.Entities.Users), true)]

#endregion

namespace ALFA_Client.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AlfaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AlfaEntities object using the connection string found in the 'AlfaEntities' section of the application configuration file.
        /// </summary>
        public AlfaEntities() : base("name=AlfaEntities", "AlfaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AlfaEntities object.
        /// </summary>
        public AlfaEntities(string connectionString) : base(connectionString, "AlfaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AlfaEntities object.
        /// </summary>
        public AlfaEntities(EntityConnection connection) : base(connection, "AlfaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CellGroup> CellGroup
        {
            get
            {
                if ((_CellGroup == null))
                {
                    _CellGroup = base.CreateObjectSet<CellGroup>("CellGroup");
                }
                return _CellGroup;
            }
        }
        private ObjectSet<CellGroup> _CellGroup;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Floors> Floors
        {
            get
            {
                if ((_Floors == null))
                {
                    _Floors = base.CreateObjectSet<Floors>("Floors");
                }
                return _Floors;
            }
        }
        private ObjectSet<Floors> _Floors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Keys> Keys
        {
            get
            {
                if ((_Keys == null))
                {
                    _Keys = base.CreateObjectSet<Keys>("Keys");
                }
                return _Keys;
            }
        }
        private ObjectSet<Keys> _Keys;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<logRecs> logRecs
        {
            get
            {
                if ((_logRecs == null))
                {
                    _logRecs = base.CreateObjectSet<logRecs>("logRecs");
                }
                return _logRecs;
            }
        }
        private ObjectSet<logRecs> _logRecs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RoomCategories> RoomCategories
        {
            get
            {
                if ((_RoomCategories == null))
                {
                    _RoomCategories = base.CreateObjectSet<RoomCategories>("RoomCategories");
                }
                return _RoomCategories;
            }
        }
        private ObjectSet<RoomCategories> _RoomCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rooms> Rooms
        {
            get
            {
                if ((_Rooms == null))
                {
                    _Rooms = base.CreateObjectSet<Rooms>("Rooms");
                }
                return _Rooms;
            }
        }
        private ObjectSet<Rooms> _Rooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CellGroup EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCellGroup(CellGroup cellGroup)
        {
            base.AddObject("CellGroup", cellGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Floors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFloors(Floors floors)
        {
            base.AddObject("Floors", floors);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Keys EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKeys(Keys keys)
        {
            base.AddObject("Keys", keys);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logRecs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologRecs(logRecs logRecs)
        {
            base.AddObject("logRecs", logRecs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RoomCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoomCategories(RoomCategories roomCategories)
        {
            base.AddObject("RoomCategories", roomCategories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRooms(Rooms rooms)
        {
            base.AddObject("Rooms", rooms);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlfaModel", Name="CellGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CellGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CellGroup object.
        /// </summary>
        /// <param name="cellGroupID">Initial value of the CellGroupID property.</param>
        public static CellGroup CreateCellGroup(global::System.Int32 cellGroupID)
        {
            CellGroup cellGroup = new CellGroup();
            cellGroup.CellGroupID = cellGroupID;
            return cellGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CellGroupID
        {
            get
            {
                return _CellGroupID;
            }
            set
            {
                if (_CellGroupID != value)
                {
                    OnCellGroupIDChanging(value);
                    ReportPropertyChanging("CellGroupID");
                    _CellGroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CellGroupID");
                    OnCellGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _CellGroupID;
        partial void OnCellGroupIDChanging(global::System.Int32 value);
        partial void OnCellGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CellID
        {
            get
            {
                return _CellID;
            }
            set
            {
                OnCellIDChanging(value);
                ReportPropertyChanging("CellID");
                _CellID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CellID");
                OnCellIDChanged();
            }
        }
        private global::System.String _CellID;
        partial void OnCellIDChanging(global::System.String value);
        partial void OnCellIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Primech
        {
            get
            {
                return _Primech;
            }
            set
            {
                OnPrimechChanging(value);
                ReportPropertyChanging("Primech");
                _Primech = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Primech");
                OnPrimechChanged();
            }
        }
        private global::System.String _Primech;
        partial void OnPrimechChanging(global::System.String value);
        partial void OnPrimechChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Users_CellGroup", "Users")]
        public EntityCollection<Users> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Users>("AlfaModel.FK_Users_CellGroup", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Users>("AlfaModel.FK_Users_CellGroup", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlfaModel", Name="Floors")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Floors : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Floors object.
        /// </summary>
        /// <param name="floorId">Initial value of the FloorId property.</param>
        public static Floors CreateFloors(global::System.Int32 floorId)
        {
            Floors floors = new Floors();
            floors.FloorId = floorId;
            return floors;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FloorId
        {
            get
            {
                return _FloorId;
            }
            set
            {
                if (_FloorId != value)
                {
                    OnFloorIdChanging(value);
                    ReportPropertyChanging("FloorId");
                    _FloorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FloorId");
                    OnFloorIdChanged();
                }
            }
        }
        private global::System.Int32 _FloorId;
        partial void OnFloorIdChanging(global::System.Int32 value);
        partial void OnFloorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FloorName
        {
            get
            {
                return _FloorName;
            }
            set
            {
                OnFloorNameChanging(value);
                ReportPropertyChanging("FloorName");
                _FloorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FloorName");
                OnFloorNameChanged();
            }
        }
        private global::System.String _FloorName;
        partial void OnFloorNameChanging(global::System.String value);
        partial void OnFloorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IPAddress
        {
            get
            {
                return _IPAddress;
            }
            set
            {
                OnIPAddressChanging(value);
                ReportPropertyChanging("IPAddress");
                _IPAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IPAddress");
                OnIPAddressChanged();
            }
        }
        private global::System.String _IPAddress;
        partial void OnIPAddressChanging(global::System.String value);
        partial void OnIPAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ComPort
        {
            get
            {
                return _ComPort;
            }
            set
            {
                OnComPortChanging(value);
                ReportPropertyChanging("ComPort");
                _ComPort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ComPort");
                OnComPortChanged();
            }
        }
        private global::System.String _ComPort;
        partial void OnComPortChanging(global::System.String value);
        partial void OnComPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ReaderProtocol
        {
            get
            {
                return _ReaderProtocol;
            }
            set
            {
                OnReaderProtocolChanging(value);
                ReportPropertyChanging("ReaderProtocol");
                _ReaderProtocol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReaderProtocol");
                OnReaderProtocolChanged();
            }
        }
        private Nullable<global::System.Int16> _ReaderProtocol;
        partial void OnReaderProtocolChanging(Nullable<global::System.Int16> value);
        partial void OnReaderProtocolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Online
        {
            get
            {
                return _Online;
            }
            set
            {
                OnOnlineChanging(value);
                ReportPropertyChanging("Online");
                _Online = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Online");
                OnOnlineChanged();
            }
        }
        private Nullable<global::System.Boolean> _Online;
        partial void OnOnlineChanging(Nullable<global::System.Boolean> value);
        partial void OnOnlineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsPolling
        {
            get
            {
                return _IsPolling;
            }
            set
            {
                OnIsPollingChanging(value);
                ReportPropertyChanging("IsPolling");
                _IsPolling = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPolling");
                OnIsPollingChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsPolling;
        partial void OnIsPollingChanging(Nullable<global::System.Boolean> value);
        partial void OnIsPollingChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Rooms_Floors", "Rooms")]
        public EntityCollection<Rooms> Rooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Rooms>("AlfaModel.FK_Rooms_Floors", "Rooms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Rooms>("AlfaModel.FK_Rooms_Floors", "Rooms", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Users_Floor", "Users")]
        public EntityCollection<Users> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Users>("AlfaModel.FK_Users_Floor", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Users>("AlfaModel.FK_Users_Floor", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlfaModel", Name="Keys")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Keys : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Keys object.
        /// </summary>
        /// <param name="keyId">Initial value of the KeyId property.</param>
        /// <param name="cellNumber">Initial value of the CellNumber property.</param>
        /// <param name="keyCode">Initial value of the keyCode property.</param>
        /// <param name="fIO">Initial value of the FIO property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static Keys CreateKeys(global::System.Int32 keyId, global::System.Int32 cellNumber, global::System.String keyCode, global::System.String fIO, global::System.Int32 type)
        {
            Keys keys = new Keys();
            keys.KeyId = keyId;
            keys.CellNumber = cellNumber;
            keys.keyCode = keyCode;
            keys.FIO = fIO;
            keys.Type = type;
            return keys;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KeyId
        {
            get
            {
                return _KeyId;
            }
            set
            {
                if (_KeyId != value)
                {
                    OnKeyIdChanging(value);
                    ReportPropertyChanging("KeyId");
                    _KeyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KeyId");
                    OnKeyIdChanged();
                }
            }
        }
        private global::System.Int32 _KeyId;
        partial void OnKeyIdChanging(global::System.Int32 value);
        partial void OnKeyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CellNumber
        {
            get
            {
                return _CellNumber;
            }
            set
            {
                OnCellNumberChanging(value);
                ReportPropertyChanging("CellNumber");
                _CellNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CellNumber");
                OnCellNumberChanged();
            }
        }
        private global::System.Int32 _CellNumber;
        partial void OnCellNumberChanging(global::System.Int32 value);
        partial void OnCellNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String keyCode
        {
            get
            {
                return _keyCode;
            }
            set
            {
                OnkeyCodeChanging(value);
                ReportPropertyChanging("keyCode");
                _keyCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("keyCode");
                OnkeyCodeChanged();
            }
        }
        private global::System.String _keyCode;
        partial void OnkeyCodeChanging(global::System.String value);
        partial void OnkeyCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FIO
        {
            get
            {
                return _FIO;
            }
            set
            {
                OnFIOChanging(value);
                ReportPropertyChanging("FIO");
                _FIO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FIO");
                OnFIOChanged();
            }
        }
        private global::System.String _FIO;
        partial void OnFIOChanging(global::System.String value);
        partial void OnFIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GuestIdn
        {
            get
            {
                return _GuestIdn;
            }
            set
            {
                OnGuestIdnChanging(value);
                ReportPropertyChanging("GuestIdn");
                _GuestIdn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GuestIdn");
                OnGuestIdnChanged();
            }
        }
        private Nullable<global::System.Int32> _GuestIdn;
        partial void OnGuestIdnChanging(Nullable<global::System.Int32> value);
        partial void OnGuestIdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RemoveDate
        {
            get
            {
                return _RemoveDate;
            }
            set
            {
                OnRemoveDateChanging(value);
                ReportPropertyChanging("RemoveDate");
                _RemoveDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RemoveDate");
                OnRemoveDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RemoveDate;
        partial void OnRemoveDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRemoveDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusCell
        {
            get
            {
                return _StatusCell;
            }
            set
            {
                OnStatusCellChanging(value);
                ReportPropertyChanging("StatusCell");
                _StatusCell = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusCell");
                OnStatusCellChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusCell;
        partial void OnStatusCellChanging(Nullable<global::System.Int32> value);
        partial void OnStatusCellChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoomId
        {
            get
            {
                return _RoomId;
            }
            set
            {
                OnRoomIdChanging(value);
                ReportPropertyChanging("RoomId");
                _RoomId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoomId");
                OnRoomIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoomId;
        partial void OnRoomIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoomIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Keys_Rooms", "Rooms")]
        public Rooms Rooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rooms>("AlfaModel.FK_Keys_Rooms", "Rooms").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rooms>("AlfaModel.FK_Keys_Rooms", "Rooms").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rooms> RoomsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rooms>("AlfaModel.FK_Keys_Rooms", "Rooms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rooms>("AlfaModel.FK_Keys_Rooms", "Rooms", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Keys_Users", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AlfaModel.FK_Keys_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AlfaModel.FK_Keys_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AlfaModel.FK_Keys_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("AlfaModel.FK_Keys_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlfaModel", Name="logRecs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class logRecs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new logRecs object.
        /// </summary>
        /// <param name="logId">Initial value of the LogId property.</param>
        /// <param name="dateLog">Initial value of the DateLog property.</param>
        public static logRecs CreatelogRecs(global::System.Int32 logId, global::System.DateTime dateLog)
        {
            logRecs logRecs = new logRecs();
            logRecs.LogId = logId;
            logRecs.DateLog = dateLog;
            return logRecs;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogId
        {
            get
            {
                return _LogId;
            }
            set
            {
                if (_LogId != value)
                {
                    OnLogIdChanging(value);
                    ReportPropertyChanging("LogId");
                    _LogId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LogId");
                    OnLogIdChanged();
                }
            }
        }
        private global::System.Int32 _LogId;
        partial void OnLogIdChanging(global::System.Int32 value);
        partial void OnLogIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateLog
        {
            get
            {
                return _DateLog;
            }
            set
            {
                OnDateLogChanging(value);
                ReportPropertyChanging("DateLog");
                _DateLog = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateLog");
                OnDateLogChanged();
            }
        }
        private global::System.DateTime _DateLog;
        partial void OnDateLogChanging(global::System.DateTime value);
        partial void OnDateLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.String _Class;
        partial void OnClassChanging(global::System.String value);
        partial void OnClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubClass
        {
            get
            {
                return _SubClass;
            }
            set
            {
                OnSubClassChanging(value);
                ReportPropertyChanging("SubClass");
                _SubClass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubClass");
                OnSubClassChanged();
            }
        }
        private global::System.String _SubClass;
        partial void OnSubClassChanging(global::System.String value);
        partial void OnSubClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String operation
        {
            get
            {
                return _operation;
            }
            set
            {
                OnoperationChanging(value);
                ReportPropertyChanging("operation");
                _operation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("operation");
                OnoperationChanged();
            }
        }
        private global::System.String _operation;
        partial void OnoperationChanging(global::System.String value);
        partial void OnoperationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoomId
        {
            get
            {
                return _RoomId;
            }
            set
            {
                OnRoomIdChanging(value);
                ReportPropertyChanging("RoomId");
                _RoomId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoomId");
                OnRoomIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoomId;
        partial void OnRoomIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoomIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_logRecs_Rooms", "Rooms")]
        public Rooms Rooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rooms>("AlfaModel.FK_logRecs_Rooms", "Rooms").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rooms>("AlfaModel.FK_logRecs_Rooms", "Rooms").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rooms> RoomsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rooms>("AlfaModel.FK_logRecs_Rooms", "Rooms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rooms>("AlfaModel.FK_logRecs_Rooms", "Rooms", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_logRecs_Users", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AlfaModel.FK_logRecs_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AlfaModel.FK_logRecs_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("AlfaModel.FK_logRecs_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("AlfaModel.FK_logRecs_Users", "Users", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlfaModel", Name="RoomCategories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RoomCategories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RoomCategories object.
        /// </summary>
        /// <param name="roomCategoriesId">Initial value of the RoomCategoriesId property.</param>
        public static RoomCategories CreateRoomCategories(global::System.Int32 roomCategoriesId)
        {
            RoomCategories roomCategories = new RoomCategories();
            roomCategories.RoomCategoriesId = roomCategoriesId;
            return roomCategories;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoomCategoriesId
        {
            get
            {
                return _RoomCategoriesId;
            }
            set
            {
                if (_RoomCategoriesId != value)
                {
                    OnRoomCategoriesIdChanging(value);
                    ReportPropertyChanging("RoomCategoriesId");
                    _RoomCategoriesId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoomCategoriesId");
                    OnRoomCategoriesIdChanged();
                }
            }
        }
        private global::System.Int32 _RoomCategoriesId;
        partial void OnRoomCategoriesIdChanging(global::System.Int32 value);
        partial void OnRoomCategoriesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryNumber
        {
            get
            {
                return _CategoryNumber;
            }
            set
            {
                OnCategoryNumberChanging(value);
                ReportPropertyChanging("CategoryNumber");
                _CategoryNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryNumber");
                OnCategoryNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryNumber;
        partial void OnCategoryNumberChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CategoryName
        {
            get
            {
                return _CategoryName;
            }
            set
            {
                OnCategoryNameChanging(value);
                ReportPropertyChanging("CategoryName");
                _CategoryName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CategoryName");
                OnCategoryNameChanged();
            }
        }
        private global::System.String _CategoryName;
        partial void OnCategoryNameChanging(global::System.String value);
        partial void OnCategoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CellCount
        {
            get
            {
                return _CellCount;
            }
            set
            {
                OnCellCountChanging(value);
                ReportPropertyChanging("CellCount");
                _CellCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CellCount");
                OnCellCountChanged();
            }
        }
        private Nullable<global::System.Int32> _CellCount;
        partial void OnCellCountChanging(Nullable<global::System.Int32> value);
        partial void OnCellCountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Room_Categories", "Rooms")]
        public EntityCollection<Rooms> Rooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Rooms>("AlfaModel.FK_Room_Categories", "Rooms");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Rooms>("AlfaModel.FK_Room_Categories", "Rooms", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlfaModel", Name="Rooms")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rooms : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rooms object.
        /// </summary>
        /// <param name="roomId">Initial value of the RoomId property.</param>
        /// <param name="conrollerId">Initial value of the ConrollerId property.</param>
        public static Rooms CreateRooms(global::System.Int32 roomId, global::System.Int16 conrollerId)
        {
            Rooms rooms = new Rooms();
            rooms.RoomId = roomId;
            rooms.ConrollerId = conrollerId;
            return rooms;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoomId
        {
            get
            {
                return _RoomId;
            }
            set
            {
                if (_RoomId != value)
                {
                    OnRoomIdChanging(value);
                    ReportPropertyChanging("RoomId");
                    _RoomId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoomId");
                    OnRoomIdChanged();
                }
            }
        }
        private global::System.Int32 _RoomId;
        partial void OnRoomIdChanging(global::System.Int32 value);
        partial void OnRoomIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FloorId
        {
            get
            {
                return _FloorId;
            }
            set
            {
                OnFloorIdChanging(value);
                ReportPropertyChanging("FloorId");
                _FloorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FloorId");
                OnFloorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _FloorId;
        partial void OnFloorIdChanging(Nullable<global::System.Int32> value);
        partial void OnFloorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoomNumber
        {
            get
            {
                return _RoomNumber;
            }
            set
            {
                OnRoomNumberChanging(value);
                ReportPropertyChanging("RoomNumber");
                _RoomNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoomNumber");
                OnRoomNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _RoomNumber;
        partial void OnRoomNumberChanging(Nullable<global::System.Int32> value);
        partial void OnRoomNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Protocol
        {
            get
            {
                return _Protocol;
            }
            set
            {
                OnProtocolChanging(value);
                ReportPropertyChanging("Protocol");
                _Protocol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Protocol");
                OnProtocolChanged();
            }
        }
        private Nullable<global::System.Int16> _Protocol;
        partial void OnProtocolChanging(Nullable<global::System.Int16> value);
        partial void OnProtocolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ConrollerId
        {
            get
            {
                return _ConrollerId;
            }
            set
            {
                OnConrollerIdChanging(value);
                ReportPropertyChanging("ConrollerId");
                _ConrollerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConrollerId");
                OnConrollerIdChanged();
            }
        }
        private global::System.Int16 _ConrollerId;
        partial void OnConrollerIdChanging(global::System.Int16 value);
        partial void OnConrollerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> LightOn
        {
            get
            {
                return _LightOn;
            }
            set
            {
                OnLightOnChanging(value);
                ReportPropertyChanging("LightOn");
                _LightOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LightOn");
                OnLightOnChanged();
            }
        }
        private Nullable<global::System.Boolean> _LightOn;
        partial void OnLightOnChanging(Nullable<global::System.Boolean> value);
        partial void OnLightOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoomClass
        {
            get
            {
                return _RoomClass;
            }
            set
            {
                OnRoomClassChanging(value);
                ReportPropertyChanging("RoomClass");
                _RoomClass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoomClass");
                OnRoomClassChanged();
            }
        }
        private global::System.String _RoomClass;
        partial void OnRoomClassChanging(global::System.String value);
        partial void OnRoomClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateGuardOn
        {
            get
            {
                return _DateGuardOn;
            }
            set
            {
                OnDateGuardOnChanging(value);
                ReportPropertyChanging("DateGuardOn");
                _DateGuardOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateGuardOn");
                OnDateGuardOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateGuardOn;
        partial void OnDateGuardOnChanging(Nullable<global::System.DateTime> value);
        partial void OnDateGuardOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OnLine
        {
            get
            {
                return _OnLine;
            }
            set
            {
                OnOnLineChanging(value);
                ReportPropertyChanging("OnLine");
                _OnLine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OnLine");
                OnOnLineChanged();
            }
        }
        private Nullable<global::System.Boolean> _OnLine;
        partial void OnOnLineChanging(Nullable<global::System.Boolean> value);
        partial void OnOnLineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Dat1
        {
            get
            {
                return _Dat1;
            }
            set
            {
                OnDat1Changing(value);
                ReportPropertyChanging("Dat1");
                _Dat1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dat1");
                OnDat1Changed();
            }
        }
        private Nullable<global::System.Boolean> _Dat1;
        partial void OnDat1Changing(Nullable<global::System.Boolean> value);
        partial void OnDat1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateDat1
        {
            get
            {
                return _DateDat1;
            }
            set
            {
                OnDateDat1Changing(value);
                ReportPropertyChanging("DateDat1");
                _DateDat1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDat1");
                OnDateDat1Changed();
            }
        }
        private Nullable<global::System.DateTime> _DateDat1;
        partial void OnDateDat1Changing(Nullable<global::System.DateTime> value);
        partial void OnDateDat1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Dat2
        {
            get
            {
                return _Dat2;
            }
            set
            {
                OnDat2Changing(value);
                ReportPropertyChanging("Dat2");
                _Dat2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Dat2");
                OnDat2Changed();
            }
        }
        private Nullable<global::System.Boolean> _Dat2;
        partial void OnDat2Changing(Nullable<global::System.Boolean> value);
        partial void OnDat2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateDat2
        {
            get
            {
                return _DateDat2;
            }
            set
            {
                OnDateDat2Changing(value);
                ReportPropertyChanging("DateDat2");
                _DateDat2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateDat2");
                OnDateDat2Changed();
            }
        }
        private Nullable<global::System.DateTime> _DateDat2;
        partial void OnDateDat2Changing(Nullable<global::System.DateTime> value);
        partial void OnDateDat2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateRemove
        {
            get
            {
                return _DateRemove;
            }
            set
            {
                OnDateRemoveChanging(value);
                ReportPropertyChanging("DateRemove");
                _DateRemove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateRemove");
                OnDateRemoveChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateRemove;
        partial void OnDateRemoveChanging(Nullable<global::System.DateTime> value);
        partial void OnDateRemoveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoomCategoriesId
        {
            get
            {
                return _RoomCategoriesId;
            }
            set
            {
                OnRoomCategoriesIdChanging(value);
                ReportPropertyChanging("RoomCategoriesId");
                _RoomCategoriesId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoomCategoriesId");
                OnRoomCategoriesIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RoomCategoriesId;
        partial void OnRoomCategoriesIdChanging(Nullable<global::System.Int32> value);
        partial void OnRoomCategoriesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsProtected
        {
            get
            {
                return _IsProtected;
            }
            set
            {
                OnIsProtectedChanging(value);
                ReportPropertyChanging("IsProtected");
                _IsProtected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsProtected");
                OnIsProtectedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsProtected;
        partial void OnIsProtectedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsProtectedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Rooms_Floors", "Floors")]
        public Floors Floors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Floors>("AlfaModel.FK_Rooms_Floors", "Floors").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Floors>("AlfaModel.FK_Rooms_Floors", "Floors").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Floors> FloorsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Floors>("AlfaModel.FK_Rooms_Floors", "Floors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Floors>("AlfaModel.FK_Rooms_Floors", "Floors", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Keys_Rooms", "Keys")]
        public EntityCollection<Keys> Keys
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Keys>("AlfaModel.FK_Keys_Rooms", "Keys");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Keys>("AlfaModel.FK_Keys_Rooms", "Keys", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_logRecs_Rooms", "logRecs")]
        public EntityCollection<logRecs> logRecs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<logRecs>("AlfaModel.FK_logRecs_Rooms", "logRecs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<logRecs>("AlfaModel.FK_logRecs_Rooms", "logRecs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Room_Categories", "RoomCategories")]
        public RoomCategories RoomCategories
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomCategories>("AlfaModel.FK_Room_Categories", "RoomCategories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomCategories>("AlfaModel.FK_Room_Categories", "RoomCategories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<RoomCategories> RoomCategoriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<RoomCategories>("AlfaModel.FK_Room_Categories", "RoomCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<RoomCategories>("AlfaModel.FK_Room_Categories", "RoomCategories", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlfaModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static Users CreateUsers(global::System.Int32 userId, global::System.DateTime created, global::System.String login, global::System.String password, global::System.String userName)
        {
            Users users = new Users();
            users.UserId = userId;
            users.Created = created;
            users.Login = login;
            users.Password = password;
            users.UserName = userName;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Remove
        {
            get
            {
                return _Remove;
            }
            set
            {
                OnRemoveChanging(value);
                ReportPropertyChanging("Remove");
                _Remove = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Remove");
                OnRemoveChanged();
            }
        }
        private Nullable<global::System.DateTime> _Remove;
        partial void OnRemoveChanging(Nullable<global::System.DateTime> value);
        partial void OnRemoveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> GuardOn
        {
            get
            {
                return _GuardOn;
            }
            set
            {
                OnGuardOnChanging(value);
                ReportPropertyChanging("GuardOn");
                _GuardOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GuardOn");
                OnGuardOnChanged();
            }
        }
        private Nullable<global::System.Boolean> _GuardOn;
        partial void OnGuardOnChanging(Nullable<global::System.Boolean> value);
        partial void OnGuardOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoomCategories
        {
            get
            {
                return _RoomCategories;
            }
            set
            {
                OnRoomCategoriesChanging(value);
                ReportPropertyChanging("RoomCategories");
                _RoomCategories = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoomCategories");
                OnRoomCategoriesChanged();
            }
        }
        private global::System.String _RoomCategories;
        partial void OnRoomCategoriesChanging(global::System.String value);
        partial void OnRoomCategoriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AlarmOn
        {
            get
            {
                return _AlarmOn;
            }
            set
            {
                OnAlarmOnChanging(value);
                ReportPropertyChanging("AlarmOn");
                _AlarmOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AlarmOn");
                OnAlarmOnChanged();
            }
        }
        private Nullable<global::System.Boolean> _AlarmOn;
        partial void OnAlarmOnChanging(Nullable<global::System.Boolean> value);
        partial void OnAlarmOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> KeyOnOff
        {
            get
            {
                return _KeyOnOff;
            }
            set
            {
                OnKeyOnOffChanging(value);
                ReportPropertyChanging("KeyOnOff");
                _KeyOnOff = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KeyOnOff");
                OnKeyOnOffChanged();
            }
        }
        private Nullable<global::System.Boolean> _KeyOnOff;
        partial void OnKeyOnOffChanging(Nullable<global::System.Boolean> value);
        partial void OnKeyOnOffChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DatX
        {
            get
            {
                return _DatX;
            }
            set
            {
                OnDatXChanging(value);
                ReportPropertyChanging("DatX");
                _DatX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DatX");
                OnDatXChanged();
            }
        }
        private Nullable<global::System.Boolean> _DatX;
        partial void OnDatXChanging(Nullable<global::System.Boolean> value);
        partial void OnDatXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CellGroupID
        {
            get
            {
                return _CellGroupID;
            }
            set
            {
                OnCellGroupIDChanging(value);
                ReportPropertyChanging("CellGroupID");
                _CellGroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CellGroupID");
                OnCellGroupIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CellGroupID;
        partial void OnCellGroupIDChanging(Nullable<global::System.Int32> value);
        partial void OnCellGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FloorId
        {
            get
            {
                return _FloorId;
            }
            set
            {
                OnFloorIdChanging(value);
                ReportPropertyChanging("FloorId");
                _FloorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FloorId");
                OnFloorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _FloorId;
        partial void OnFloorIdChanging(Nullable<global::System.Int32> value);
        partial void OnFloorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Users_CellGroup", "CellGroup")]
        public CellGroup CellGroup
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CellGroup>("AlfaModel.FK_Users_CellGroup", "CellGroup").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CellGroup>("AlfaModel.FK_Users_CellGroup", "CellGroup").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CellGroup> CellGroupReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CellGroup>("AlfaModel.FK_Users_CellGroup", "CellGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CellGroup>("AlfaModel.FK_Users_CellGroup", "CellGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Keys_Users", "Keys")]
        public EntityCollection<Keys> Keys
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Keys>("AlfaModel.FK_Keys_Users", "Keys");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Keys>("AlfaModel.FK_Keys_Users", "Keys", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_logRecs_Users", "logRecs")]
        public EntityCollection<logRecs> logRecs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<logRecs>("AlfaModel.FK_logRecs_Users", "logRecs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<logRecs>("AlfaModel.FK_logRecs_Users", "logRecs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlfaModel", "FK_Users_Floor", "Floors")]
        public Floors Floors
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Floors>("AlfaModel.FK_Users_Floor", "Floors").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Floors>("AlfaModel.FK_Users_Floor", "Floors").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Floors> FloorsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Floors>("AlfaModel.FK_Users_Floor", "Floors");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Floors>("AlfaModel.FK_Users_Floor", "Floors", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
